globalvar TILE_PADDING_CAP, PLAY_AREA_PADDING, HOVER_SCALE, GAME_OFFSET_X, WIN_WIDTH, WIN_HEIGHT, TWEEN_SPEED;
TILE_PADDING_CAP = 24;
PLAY_AREA_PADDING = 24;
HOVER_SCALE = 1.1;
GAME_OFFSET_X = 100;
WIN_WIDTH = 800;
WIN_HEIGHT = 600;
TWEEN_SPEED = .08;
